repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.devcontainer/.tflint.hcl
          - --args=--format=compact
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-write=true
      - id: terraform_trivy
      - id: terraform_checkov
        args:
          - --args=--framework=terraform,github_actions,terraform_plan
          - --args=--output=cli
          - --args=--soft-fail

  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.3'
    hooks:
      - id: bandit
        name: Bandit Python security check
        args: ["-r", "src/"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
