name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for Gitleaks to scan git history
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit[sarif]
    
    - name: Run Bandit security scan
      run: |
        bandit -r src/
      continue-on-error: true  # Allow the workflow to continue even if issues are found
    
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Bandit SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: bandit-results.sarif
        category: bandit