name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit[sarif]
    
    - name: Run Bandit security scan
      run: |
        bandit -r src/ -f sarif -o bandit-results.sarif -ll
      continue-on-error: true  # Allow the workflow to continue even if issues are found
    
    - name: Check for hardcoded secrets
      run: |
        # Using grep to look for potential hardcoded secrets
        echo "Checking for potential hardcoded secrets..."
        grep -r -E "(password|secret|key|token|credential)" src/ || true
    
    - name: Upload Checkov SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: bandit-results.sarif
        category: bandit