name: "XX - Terraform Security Scan"

on:
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  security-scan:
    name: "Terraform Security Scan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov Action - Terraform
        id: checkov-terraform
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          framework: terraform,terraform_plan
          output_format: cli,sarif
          output_file_path: console,results_checkov_terraform.sarif
          soft_fail: true

      - name: Upload Checkov SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results_checkov_terraform.sarif
          category: terraform-checkov
      
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      
      - name: Run KICS Action
        uses: checkmarx/kics-github-action@v2.1.5
        with:
          path: 'terraform'
          output_formats: 'json,sarif'
          platform_type: 'terraform'
          output_path: results-dir
          ignore_on_exit: results

      - name: Upload KICS SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results-dir/results.sarif
          category: terraform-kics

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

